version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    volumes:
      - ./admin:/app
      - ./frontend/content/blog:/app/blog_content
      - ./admin/static:/app/staticfiles
    environment:
      - DJANGO_STATIC_ROOT=/usr/share/nginx/static
      - PYTHONPATH=/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  ursus:
    build:
      context: .
      dockerfile: Dockerfile.ursus
    volumes:
      - ./ursus:/app/ursus
      - ./bin/ursus:/app/bin/ursus:ro
      - ./frontend/content:/app/frontend/content:ro
      - ./frontend/templates:/app/frontend/templates:ro
      - ./output:/app/output
      - ./ursus_config.py:/app/ursus_config.py:ro   
      - ./.git:/app/.git:ro
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    command: ["python", "./bin/ursus"]

  ai:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app
      - ./frontend/content/blog:/app/blog_content 
      - ./bin/ursus:/app/bin/ursus:ro
    env_file:
      - .env

  static:
    image: nginx:alpine
    container_name: static_site
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./admin/static:/usr/share/nginx/static:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
