# Dockerfile.ursus

FROM python:3.11-slim

WORKDIR /app

COPY ./ursus/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./ursus ./ursus

COPY ./bin/ursus /app/bin/ursus

RUN chmod +x /app/bin/ursus

RUN pip install .

CMD ["python", "./bin/ursus"]