name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create target directory if not exists
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p /var/www/blog

    - name: Upload .env file
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "${{ secrets.ENV_FILE }}" > /var/www/blog/.env

    - name: Copy project files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/var/www/blog"

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/blog
          docker-compose down
          docker-compose up -d --build
      timeout-minutes: 30 

    - name: Wait until sitemap.xml is accessible
      run: |
        for i in {1..30}; do
          curl --fail --silent https://blog.emirbaycan.com.tr/sitemap.xml && break || sleep 3
        done

    - name: Ping Bing with new sitemap
      run: |
        curl "https://www.bing.com/ping?sitemap=https://blog.emirbaycan.com.tr/sitemap.xml"

    - name: Ping Yandex with new sitemap
      run: |
        curl "https://webmaster.yandex.com/ping?sitemap=https://blog.emirbaycan.com.tr/sitemap.xml"